export const GET_SEARCH_TERM = 'GET_SEARCH_TERM';
export const GET_ADVANCED_SEARCH_RESULTS = 'GET_ADVANCED_SEARCH_RESULTS';
export const ADD_USER_REVIEW = 'ADD_USER_REVIEW';
export const LOADER_RESET = 'LOADER_RESET';